### ISSUE TITLE
ami provision

### ISSUE THREAD

**Issue by iteratelance** [iterateco/ansible#3]
We should be able to create an AMI using the new ansible framework for the following project:

https://github.com/iterateco/ebyline-api

It's ebyline AWS console https://ebyline.signin.aws.amazon.com/console

Let me know if you need a login.  Once logged in you'll be able to create AWS keys.

You will have to set the following environment variables in order to work properly

```
export AWS_ACCESS_KEY_ID='XXXX'
export AWS_SECRET_ACCESS_KEY='XXX'
export EC2_OVERRIDE_DESTVAR='public'
```

Hiep added this variable EC2_OVERRIDE_DESTVAR but it could also be set in ec2.ini 

```
vpc_destination_variable = private_ip_address
#vpc_destination_variable = ip_address
```

Please note that I think it might be better to store ec2.ini file in project ansible directory and commit to github.

Then we could possibly do something like this.

```
export EC2_INI_PATH=/path/to/my_ec2.ini
```

Maybe we check in the entire inventory folder into the project?  What do you think?

**Comment by mzxe** [comment]
create pull request #12
